theme: jekyll-theme-midnight
title: Welcome to my page
description: My name is Vianesse, recently certified with technical expertise and coding skills needed to work as a full stack software consultant. Skills: Core Java, ProstgreSQL, Java Script, HTML.
description: https://www.linkedin.com/in/vianesse-gonzalez/
description: Please, feel free to look at my two showcase videos and request to see the code.
