theme: jekyll-theme-midnight
title: Welcome to my page
description: My name is Vianesse, recently certified with technical expertise and coding skills needed to work as a full stack software consultant.

